server:
  port: 8761

# http://localhost:8761 is the url of the service registry
# this is a registry. so do not self register
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}
    fetch-registry: false
    register-with-eureka: false
