server:
  port: 8081

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/

#database specific properties
#hibernate specific properties

spring:
  application:
    name: MOBILE-SERVICE
#  datasource:
#    url: jdbc:mysql://localhost:3306/relations
#    username: root
#    password: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#    show-sql: true
  config:
    import: configserver:http://localhost:8888/
  profiles:
    active: dev