server:
  port: 8082

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/

#database specific properties
#hibernate specific properties

spring:
  application:
    name: CART-SERVICE
